In [556]:
import pandas as pd
import numpy as np

In [557]:
users_df = pd.read_csv('data_warehouse/staging/users_staging.csv')
course_progress_df = pd.read_csv('data_warehouse/staging/course_progress_staging.csv')
module_progress_df = pd.read_csv('data_warehouse/staging/module_progress_staging.csv')
courses_df = pd.read_csv('data_warehouse/staging/courses_staging.csv')
course_modules_df = pd.read_csv('data_warehouse/staging/modules_staging.csv')

In [558]:
display(users_df)
list(users_df.columns)

,user_id,name,email,designation,created_at
0,44cc867d-259e-4c2e-875b-b2b4eb9b1eee,Stephen Gallagher,timothysmith@example.net,DevOps Engineer,2024-01-06 21:10:42
1,872c64ac-d1d6-4afd-b9bb-157bfd40756e,Lori Cameron,teresa05@example.org,Cybersecurity Specialist,2024-02-28 03:35:01
2,5ec3ba72-a086-466d-9d4d-f7d57d09027b,William Rivera,porterbruce@example.net,DevOps Engineer,2024-01-21 08:21:18
3,350b029b-6711-4566-8406-073a7f339b3e,Robert Gutierrez,griley@example.net,Cybersecurity Specialist,2024-09-22 12:07:01
4,89403c9e-3b6a-442c-96c7-89ec7e01f763,Erik Johnson,jacobbennett@example.com,UI/UX Designer,2024-02-27 19:58:38
...,...,...,...,...,...
95,4659ddba-6741-44c0-8ec2-01522dc5b1e0,Leslie Lee,nkelly@example.org,Mobile Developer,2024-04-19 20:31:14
96,51a7224d-0ff5-4919-939f-70634b99535c,Stephanie Ramsey,fredwarren@example.com,Mobile Developer,2024-04-05 16:02:30
97,028d0ea0-c7cb-40f0-a0da-f2a53888dd37,Charles Sanders,robertday@example.com,Web Developer,2024-05-25 07:50:24
98,23784ed5-0039-453c-818f-9a8dc34e6bb3,Haley Frazier,rsmith@example.com,Cybersecurity Specialist,2024-10-04 02:35:52
99,f36fa2be-3862-46e4-aefc-2b7a984b1406,Isabella Fields,mayjoshua@example.net,DevOps Engineer,2024-02-20 05:35:31

['user_id', 'name', 'email', 'designation', 'created_at']

In [559]:
display(course_progress_df)
list(course_progress_df.columns)

,progress_id,employee_id,course_id,completion_percentage,score,completed_at
0,0f6159ee-2e65-4a82-8ca9-03455c6db142,44cc867d-259e-4c2e-875b-b2b4eb9b1eee,3f4c255a-3ed2-4c07-8b82-3fb30c863226,12,69,NaN
1,e57919de-d9fb-4469-b6da-656d24c8cac1,44cc867d-259e-4c2e-875b-b2b4eb9b1eee,6a52ebe0-0cd7-41a8-b825-3704194741a0,46,20,NaN
2,f58da2be-2b19-4f00-aa20-30eefa7992f7,44cc867d-259e-4c2e-875b-b2b4eb9b1eee,fc64aa01-38bb-4ccf-b446-869c1fd3fcf1,73,58,NaN
3,44930adf-b897-48b9-80bd-493bae511248,44cc867d-259e-4c2e-875b-b2b4eb9b1eee,2191c368-9102-4d66-a668-5ccf7d317509,80,79,NaN
4,7f821525-4f8f-4342-b571-43c41c2f19c7,44cc867d-259e-4c2e-875b-b2b4eb9b1eee,db152902-82d6-4ba2-aa87-f7aa9faf0d69,52,100,NaN
...,...,...,...,...,...,...
1995,62f7e076-b2f3-4060-927e-40daf0e844ba,f36fa2be-3862-46e4-aefc-2b7a984b1406,b126a3f1-2b94-4de0-8e8f-596f478c7de3,41,46,NaN
1996,2229e09f-1825-41e7-82c6-50ff6c337438,f36fa2be-3862-46e4-aefc-2b7a984b1406,df04b2a3-7c27-4f33-b4bd-fdf102fd0f01,27,89,NaN
1997,227f9112-ae12-41af-927a-7a5df536cd24,f36fa2be-3862-46e4-aefc-2b7a984b1406,fdfb691a-6314-4d16-85d7-a19611600b8a,32,59,NaN
1998,a0f9dd3b-9e95-4770-b120-f0c010773203,f36fa2be-3862-46e4-aefc-2b7a984b1406,699a90ef-bd36-4eb4-8286-15d8ff970eda,32,42,NaN
1999,004ccb58-5c2f-44f1-aa9d-a369deca4abb,f36fa2be-3862-46e4-aefc-2b7a984b1406,6e14ec87-40fe-4809-b762-daa4db93dd3f,76,24,NaN

['progress_id',
 'employee_id',
 'course_id',
 'completion_percentage',
 'score',
 'completed_at']

In [560]:
display(module_progress_df)
list(module_progress_df.columns)

,module_progress_id,employee_id,course_id,module_id,is_completed,completed_at
0,ede9ae99-1cef-43ce-912a-f716fd8b00cf,44cc867d-259e-4c2e-875b-b2b4eb9b1eee,38782344-4b97-4ab7-a03f-dd9c9e236ffb,af02757d-39d1-4f23-884d-f3596ced1cea,0,NaN
1,1f508a88-00cf-4c57-a4a0-b1d76146a518,44cc867d-259e-4c2e-875b-b2b4eb9b1eee,30197a42-f77e-49c2-8946-4bbd36fbf79d,000925fe-e139-4643-b64a-6265fd5775e4,0,NaN
2,949391d8-0d8b-4fa4-ac3e-5e1505362e71,44cc867d-259e-4c2e-875b-b2b4eb9b1eee,3f04b295-f148-4f74-b86f-daa8506c9048,18764a1c-f272-450c-bb20-b62191dcb1b5,0,NaN
3,141190de-9f2b-4807-838c-031a38a4f384,44cc867d-259e-4c2e-875b-b2b4eb9b1eee,ec547ddb-3fec-424b-a343-ddafec1fa0cf,e40a23c0-6f55-4b31-ad6d-a949736e8c6a,0,NaN
4,b07dcbfd-cd62-4626-a7d5-267812c49b4e,44cc867d-259e-4c2e-875b-b2b4eb9b1eee,699a90ef-bd36-4eb4-8286-15d8ff970eda,69ca931e-5af2-4a9b-8a2b-4739e299c6ca,0,NaN
...,...,...,...,...,...,...
9995,c47deb02-ac57-46fa-896f-7c133ca261f0,f36fa2be-3862-46e4-aefc-2b7a984b1406,30197a42-f77e-49c2-8946-4bbd36fbf79d,8ff7a5e0-b943-450e-8309-e0ec15b21880,0,NaN
9996,d42a7d14-8abf-4fd3-92a0-9a8641d46bd7,f36fa2be-3862-46e4-aefc-2b7a984b1406,a486147a-14bc-495f-b315-8b115d689ce1,d65efc35-97d1-415b-8b1f-ed6209c15555,0,NaN
9997,e133a475-0347-4038-b7b9-380ad4f6c9be,f36fa2be-3862-46e4-aefc-2b7a984b1406,6a52ebe0-0cd7-41a8-b825-3704194741a0,fd8b7c82-f01c-4c17-a221-cccd8f6a5690,1,2024-09-11 06:16:26
9998,fee73a43-9ad3-49ae-9895-9cd9d531dbbd,f36fa2be-3862-46e4-aefc-2b7a984b1406,df04b2a3-7c27-4f33-b4bd-fdf102fd0f01,c7bad04f-c028-40e5-a329-4f0796efee2a,0,NaN
9999,f9305462-2d5c-4895-8224-1b7638d24ee2,f36fa2be-3862-46e4-aefc-2b7a984b1406,445a1b9a-826f-4f65-90f1-7771578fac5f,872b31a2-3433-4c71-b76c-b4fbd98af4a3,1,2024-01-16 12:08:14

['module_progress_id',
 'employee_id',
 'course_id',
 'module_id',
 'is_completed',
 'completed_at']

In [561]:
display(courses_df)
list(courses_df.columns)

,course_id,title,description,duration,modules,created_at,tag
0,3f4c255a-3ed2-4c07-8b82-3fb30c863226,Ergonomic intangible adapter,Remember stay author result more few recognize...,172,1,2024-07-18 19:59:37,Data Science
1,6a52ebe0-0cd7-41a8-b825-3704194741a0,Synchronized system-worthy migration,Discussion or hard see card serious. Role boy ...,139,3,2024-08-07 08:31:40,Web Development
2,fc64aa01-38bb-4ccf-b446-869c1fd3fcf1,Adaptive context-sensitive Local Area Network,Center actually north discuss according. Attor...,75,9,2024-05-29 10:06:14,Mobile Development
3,2191c368-9102-4d66-a668-5ccf7d317509,Reverse-engineered needs-based flexibility,Two machine society research specific fill sig...,118,2,2024-06-14 13:27:47,Cybersecurity
4,db152902-82d6-4ba2-aa87-f7aa9faf0d69,Multi-tiered mission-critical implementation,Successful baby short edge. Clearly hand occur...,86,1,2024-03-16 10:05:22,Data Science
5,eee76786-5a72-4d28-9a2e-23266b968959,Digitized high-level throughput,Tree drug mother challenge own network process...,77,3,2024-05-14 18:06:58,Generative AI
6,a486147a-14bc-495f-b315-8b115d689ce1,Grass-roots tangible frame,Decision trip tax six yourself investment carr...,78,8,2024-08-13 21:10:34,DevOps
7,3f04b295-f148-4f74-b86f-daa8506c9048,Polarized needs-based success,Box level within themselves ahead to foot blue...,104,7,2024-09-11 20:26:52,Web Development
8,a3ddc761-3c41-4f7f-a56e-e575d1bc25ad,Upgradable dedicated flexibility,Chair trial check. Already edge avoid be. Look...,131,9,2024-08-22 07:03:50,Generative AI
9,38782344-4b97-4ab7-a03f-dd9c9e236ffb,Devolved hybrid structure,Ok cell serve. Nature bag assume degree fall w...,150,3,2024-07-23 03:04:02,Generative AI
10,30197a42-f77e-49c2-8946-4bbd36fbf79d,Multi-channeled stable help-desk,Yeah remain few bad process generation arrive....,151,1,2024-02-14 21:42:12,Generative AI
11,5b3b1bdd-a35d-435d-8473-0d92dd911d32,Synergistic bottom-line leverage,Radio carry between we edge. Eat herself kid. ...,101,1,2024-09-13 18:36:06,UI/UX Design
12,445a1b9a-826f-4f65-90f1-7771578fac5f,User-friendly motivating projection,Because in democratic student. I either return...,147,2,2024-08-24 06:26:51,UI/UX Design
13,ec547ddb-3fec-424b-a343-ddafec1fa0cf,Visionary asymmetric hub,On expert establish medical firm cultural amon...,95,7,2024-07-17 01:26:17,DevOps
14,55ea5fd6-c51a-4923-b390-b1957a50f298,Public-key methodical neural-net,Trip area act evening standard material. Arriv...,116,5,2024-04-10 13:20:28,UI/UX Design
15,b126a3f1-2b94-4de0-8e8f-596f478c7de3,Cross-group national framework,Million bar employee. Style leg blue oil group...,120,9,2024-04-06 13:35:27,Mobile Development
16,df04b2a3-7c27-4f33-b4bd-fdf102fd0f01,Synergized modular access,Interest rise hear the. Other question small. ...,75,9,2024-02-29 17:02:09,Data Engineering
17,fdfb691a-6314-4d16-85d7-a19611600b8a,Ameliorated responsive Local Area Network,Red American return charge room wall. Executiv...,69,3,2024-05-21 07:23:09,DevOps
18,699a90ef-bd36-4eb4-8286-15d8ff970eda,Networked asynchronous archive,Begin price international court least communit...,100,9,2024-05-05 22:17:19,DevOps
19,6e14ec87-40fe-4809-b762-daa4db93dd3f,Reverse-engineered next generation data-warehouse,Third commercial list those born story glass m...,69,4,2024-08-24 07:57:35,UI/UX Design

['course_id',
 'title',
 'description',
 'duration',
 'modules',
 'created_at',
 'tag']

In [562]:
display(course_modules_df)
list(course_modules_df.columns)

,module_id,course_id,module_title,module_content,module_duration,created_at
0,af02757d-39d1-4f23-884d-f3596ced1cea,55ea5fd6-c51a-4923-b390-b1957a50f298,Open-source radical contingency,Player too student drop institution American f...,11,2024-04-27 05:28:12
1,000925fe-e139-4643-b64a-6265fd5775e4,2191c368-9102-4d66-a668-5ccf7d317509,Operative 24hour neural-net,Whose may former appear future part. Turn reli...,12,2024-05-24 03:32:02
2,18764a1c-f272-450c-bb20-b62191dcb1b5,db152902-82d6-4ba2-aa87-f7aa9faf0d69,Open-source zero-defect data-warehouse,Job reason general hand worker listen. Feeling...,21,2024-07-03 12:29:56
3,e40a23c0-6f55-4b31-ad6d-a949736e8c6a,b126a3f1-2b94-4de0-8e8f-596f478c7de3,Optional non-volatile system engine,Soon know save successful hard seven finally r...,21,2024-08-31 20:36:18
4,69ca931e-5af2-4a9b-8a2b-4739e299c6ca,3f04b295-f148-4f74-b86f-daa8506c9048,Re-contextualized next generation system engine,Behavior wish plant later eight enjoy control ...,25,2024-08-05 22:34:29
...,...,...,...,...,...,...
95,8ff7a5e0-b943-450e-8309-e0ec15b21880,5b3b1bdd-a35d-435d-8473-0d92dd911d32,Synergistic client-driven circuit,Once she main media street cut whatever discus...,21,2024-03-14 12:07:05
96,d65efc35-97d1-415b-8b1f-ed6209c15555,3f04b295-f148-4f74-b86f-daa8506c9048,Automated real-time throughput,Food public speech win. Sort song officer lawy...,20,2024-03-03 04:25:57
97,fd8b7c82-f01c-4c17-a221-cccd8f6a5690,fc64aa01-38bb-4ccf-b446-869c1fd3fcf1,Re-engineered web-enabled project,Then can test sea member another deal. Letter ...,21,2024-08-12 04:52:38
98,c7bad04f-c028-40e5-a329-4f0796efee2a,a3ddc761-3c41-4f7f-a56e-e575d1bc25ad,Self-enabling cohesive frame,Good impact the scientist side responsibility ...,13,2024-08-06 13:45:39
99,872b31a2-3433-4c71-b76c-b4fbd98af4a3,55ea5fd6-c51a-4923-b390-b1957a50f298,Exclusive multi-tasking array,Stage rule speech land everybody change force....,13,2024-09-30 05:27:16

['module_id',
 'course_id',
 'module_title',
 'module_content',
 'module_duration',
 'created_at']

Merge dataframes

In [563]:
# Step 1: Merge users_df with course_progress_df on employee_id
merged_df = pd.merge(users_df, course_progress_df, left_on='user_id', right_on='employee_id', how='left')

# Step 2: Merge merged_df with courses_df to include course details
merged_df = pd.merge(merged_df, courses_df, on='course_id', how='left')

# Step 3: Merge module_progress_df with course_modules_df to get module details for each course
module_df = pd.merge(module_progress_df, course_modules_df, on='module_id', how='left')

# Step 4: Merge the module_df with merged_df to incorporate module completion info
final_df = pd.merge(merged_df, module_df,left_on=['user_id', 'course_id'], right_on=['employee_id', 'course_id_x'], how='left')

In [564]:
final_df = final_df[[
    'user_id', 'name', 'email', 'designation',   # From users_df
    'course_id', 'title', 'tag', 'completion_percentage', 'duration', 'score', 'completed_at_x',  # From course_progress_df and courses_df
    'module_id', 'module_title', 'is_completed', 'module_duration', 'completed_at_y'  # From module_progress_df and course_modules_df
]]

# Rename columns for clarity
final_df.rename(columns={
    'completed_at_x': 'course_completed_at',
    'completed_at_y': 'module_completed_at',
    'title': 'course_title',
    'tag': 'course_tag',
    'score': 'course_score',
    'duration': 'course_duration',
}, inplace=True)

In [565]:
final_df.columns

Index(['user_id', 'name', 'email', 'designation', 'course_id', 'course_title',
       'course_tag', 'completion_percentage', 'course_duration',
       'course_score', 'course_completed_at', 'module_id', 'module_title',
       'is_completed', 'module_duration', 'module_completed_at'],
      dtype='object')

In [566]:
final_df
# final_df.to_csv('final_df1.csv',index=False)

,user_id,name,email,designation,course_id,course_title,course_tag,completion_percentage,course_duration,course_score,course_completed_at,module_id,module_title,is_completed,module_duration,module_completed_at
0,44cc867d-259e-4c2e-875b-b2b4eb9b1eee,Stephen Gallagher,timothysmith@example.net,DevOps Engineer,3f4c255a-3ed2-4c07-8b82-3fb30c863226,Ergonomic intangible adapter,Data Science,12,172,69,NaN,d4fde19b-e050-44cc-9865-7a54f7603340,Monitored regional structure,1.0,21.0,2024-07-22 19:24:11
1,44cc867d-259e-4c2e-875b-b2b4eb9b1eee,Stephen Gallagher,timothysmith@example.net,DevOps Engineer,3f4c255a-3ed2-4c07-8b82-3fb30c863226,Ergonomic intangible adapter,Data Science,12,172,69,NaN,cf10fb47-ec3d-4de6-9071-b7b201a5a942,Optional 4thgeneration methodology,1.0,23.0,2024-02-24 21:42:47
2,44cc867d-259e-4c2e-875b-b2b4eb9b1eee,Stephen Gallagher,timothysmith@example.net,DevOps Engineer,3f4c255a-3ed2-4c07-8b82-3fb30c863226,Ergonomic intangible adapter,Data Science,12,172,69,NaN,84e726ae-f2c2-4aeb-9190-f17fdb5b2555,Centralized zero administration approach,1.0,18.0,2024-07-12 22:54:45
3,44cc867d-259e-4c2e-875b-b2b4eb9b1eee,Stephen Gallagher,timothysmith@example.net,DevOps Engineer,3f4c255a-3ed2-4c07-8b82-3fb30c863226,Ergonomic intangible adapter,Data Science,12,172,69,NaN,7fc31537-1430-47f9-98a3-0a8b157a5e44,Extended multi-state service-desk,1.0,30.0,2024-09-05 09:54:48
4,44cc867d-259e-4c2e-875b-b2b4eb9b1eee,Stephen Gallagher,timothysmith@example.net,DevOps Engineer,3f4c255a-3ed2-4c07-8b82-3fb30c863226,Ergonomic intangible adapter,Data Science,12,172,69,NaN,72b092ff-98be-4142-89ab-922b9c1fd63c,Persevering solution-oriented projection,0.0,20.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10010,f36fa2be-3862-46e4-aefc-2b7a984b1406,Isabella Fields,mayjoshua@example.net,DevOps Engineer,6e14ec87-40fe-4809-b762-daa4db93dd3f,Reverse-engineered next generation data-warehouse,UI/UX Design,76,69,24,NaN,571ef6e1-8c89-4fba-9561-d2df49616531,Persevering optimizing software,0.0,16.0,NaN
10011,f36fa2be-3862-46e4-aefc-2b7a984b1406,Isabella Fields,mayjoshua@example.net,DevOps Engineer,6e14ec87-40fe-4809-b762-daa4db93dd3f,Reverse-engineered next generation data-warehouse,UI/UX Design,76,69,24,NaN,53eb4bb7-8aae-4cdf-bcd9-05b733295aaa,Right-sized neutral circuit,1.0,18.0,2024-03-01 11:17:20
10012,f36fa2be-3862-46e4-aefc-2b7a984b1406,Isabella Fields,mayjoshua@example.net,DevOps Engineer,6e14ec87-40fe-4809-b762-daa4db93dd3f,Reverse-engineered next generation data-warehouse,UI/UX Design,76,69,24,NaN,bfc21258-ba39-471b-854d-42059ce291e8,Team-oriented 4thgeneration forecast,0.0,16.0,NaN
10013,f36fa2be-3862-46e4-aefc-2b7a984b1406,Isabella Fields,mayjoshua@example.net,DevOps Engineer,6e14ec87-40fe-4809-b762-daa4db93dd3f,Reverse-engineered next generation data-warehouse,UI/UX Design,76,69,24,NaN,4476019d-ab75-4042-9bdf-b4d83698cd99,Ergonomic full-range time-frame,1.0,28.0,2024-10-04 19:30:29
10014,f36fa2be-3862-46e4-aefc-2b7a984b1406,Isabella Fields,mayjoshua@example.net,DevOps Engineer,6e14ec87-40fe-4809-b762-daa4db93dd3f,Reverse-engineered next generation data-warehouse,UI/UX Design,76,69,24,NaN,48086c70-ebc8-47ce-8a08-1d7543d0b832,Secured explicit encryption,0.0,28.0,NaN

Employee Course KPI: This captures each employeeâ€™s course progress (average completion percentage and performance score). This will be useful for understanding how far employees have progressed in their courses and how theyâ€™re performing.

In [567]:
# Group by user and course to calculate total modules and completed modules per course
module_kpi = final_df.groupby(['user_id', 'course_id']).agg(
    total_modules=('module_id', 'count'),        # Total number of modules for the course
    modules_completed=('is_completed', 'sum')   # Number of completed modules (is_completed is 1 for completed)
).reset_index()

module_kpi.columns

display(module_kpi)

,user_id,course_id,total_modules,modules_completed
0,01f9f4d3-e268-4417-ae0b-d70326a3fb17,2191c368-9102-4d66-a668-5ccf7d317509,2,1.0
1,01f9f4d3-e268-4417-ae0b-d70326a3fb17,30197a42-f77e-49c2-8946-4bbd36fbf79d,8,3.0
2,01f9f4d3-e268-4417-ae0b-d70326a3fb17,38782344-4b97-4ab7-a03f-dd9c9e236ffb,4,3.0
3,01f9f4d3-e268-4417-ae0b-d70326a3fb17,3f04b295-f148-4f74-b86f-daa8506c9048,3,2.0
4,01f9f4d3-e268-4417-ae0b-d70326a3fb17,3f4c255a-3ed2-4c07-8b82-3fb30c863226,6,4.0
...,...,...,...,...
1995,ff5bc5cd-d4f9-42dc-a94f-7d523327425b,df04b2a3-7c27-4f33-b4bd-fdf102fd0f01,6,1.0
1996,ff5bc5cd-d4f9-42dc-a94f-7d523327425b,ec547ddb-3fec-424b-a343-ddafec1fa0cf,2,1.0
1997,ff5bc5cd-d4f9-42dc-a94f-7d523327425b,eee76786-5a72-4d28-9a2e-23266b968959,10,3.0
1998,ff5bc5cd-d4f9-42dc-a94f-7d523327425b,fc64aa01-38bb-4ccf-b446-869c1fd3fcf1,7,4.0
1999,ff5bc5cd-d4f9-42dc-a94f-7d523327425b,fdfb691a-6314-4d16-85d7-a19611600b8a,3,2.0

In [568]:
# Merge the module_kpi with the final_df to incorporate total and completed modules
final_df = pd.merge(final_df, module_kpi, on=['user_id', 'course_id'], how='left')

display(final_df.columns)

Index(['user_id', 'name', 'email', 'designation', 'course_id', 'course_title',
       'course_tag', 'completion_percentage', 'course_duration',
       'course_score', 'course_completed_at', 'module_id', 'module_title',
       'is_completed', 'module_duration', 'module_completed_at',
       'total_modules', 'modules_completed'],
      dtype='object')

In [569]:
# Calculate completed percentage for the modules
final_df['completion_percentage'] = (final_df['modules_completed'] / final_df['total_modules']) * 100

In [570]:
# Employee KPI: Each employee's course progress with total modules, completed modules, and module completion percentage
employee_course_kpi = final_df.groupby(['user_id', 'name', 'designation', 'course_id', 'course_title', 'course_tag']).agg(
    total_modules=('total_modules', 'first'),
    modules_completed=('modules_completed', 'first'),
    completion_percentage=('completion_percentage', 'first'),
    course_score=('course_score', 'first')
).reset_index()

In [571]:
def calculate_performance_score(progress_df):
    # Group by employee and calculate total score and total max score
    performance_summary = progress_df.groupby('user_id').agg(
        total_score=('course_score', 'sum'),  # Sum of course scores
        total_max_score=('course_score', lambda x: len(x) * 100),  # Assuming max score for each course is 100
        completed_courses=('completion_percentage', lambda x: (x == 100).sum())  # Count of fully completed courses
    ).reset_index()

    # Calculate performance score as a percentage
    performance_summary['performance_score'] = (performance_summary['total_score'] / performance_summary['total_max_score']) * 100
    return performance_summary

# %%
# Update performance score for each employee
performance_summary = calculate_performance_score(final_df)

In [572]:
final_df = pd.merge(final_df, performance_summary[['user_id', 'performance_score']], on='user_id', how='left')

In [573]:
final_df.to_csv('data_warehouse/report/final_df.csv', index=False)

In [574]:
final_df.columns

Index(['user_id', 'name', 'email', 'designation', 'course_id', 'course_title',
       'course_tag', 'completion_percentage', 'course_duration',
       'course_score', 'course_completed_at', 'module_id', 'module_title',
       'is_completed', 'module_duration', 'module_completed_at',
       'total_modules', 'modules_completed', 'performance_score'],
      dtype='object')

In [575]:
filtered_df = final_df[[
    'user_id', 'name', 'designation', 'course_id', 'course_title', 'course_tag',
    'course_duration','modules_completed', 'total_modules', 'completion_percentage', 'course_score', 'performance_score'
]]

In [576]:
employee_performance_kpi = filtered_df.groupby([
    'user_id', 'name', 'designation', 'course_id', 'course_title', 'course_tag', 
    'course_duration','modules_completed', 'total_modules', 'completion_percentage', 'course_score', 'performance_score'
]).first().reset_index()

display(employee_performance_kpi)

,user_id,name,designation,course_id,course_title,course_tag,course_duration,modules_completed,total_modules,completion_percentage,course_score,performance_score
0,01f9f4d3-e268-4417-ae0b-d70326a3fb17,Lucas Jackson,UI/UX Designer,2191c368-9102-4d66-a668-5ccf7d317509,Reverse-engineered needs-based flexibility,Cybersecurity,118,1.0,2,50.000000,38,49.29
1,01f9f4d3-e268-4417-ae0b-d70326a3fb17,Lucas Jackson,UI/UX Designer,30197a42-f77e-49c2-8946-4bbd36fbf79d,Multi-channeled stable help-desk,Generative AI,151,3.0,8,37.500000,86,49.29
2,01f9f4d3-e268-4417-ae0b-d70326a3fb17,Lucas Jackson,UI/UX Designer,38782344-4b97-4ab7-a03f-dd9c9e236ffb,Devolved hybrid structure,Generative AI,150,3.0,4,75.000000,84,49.29
3,01f9f4d3-e268-4417-ae0b-d70326a3fb17,Lucas Jackson,UI/UX Designer,3f04b295-f148-4f74-b86f-daa8506c9048,Polarized needs-based success,Web Development,104,2.0,3,66.666667,69,49.29
4,01f9f4d3-e268-4417-ae0b-d70326a3fb17,Lucas Jackson,UI/UX Designer,3f4c255a-3ed2-4c07-8b82-3fb30c863226,Ergonomic intangible adapter,Data Science,172,4.0,6,66.666667,22,49.29
...,...,...,...,...,...,...,...,...,...,...,...,...
1980,ff5bc5cd-d4f9-42dc-a94f-7d523327425b,Alexis Roy,Web Developer,df04b2a3-7c27-4f33-b4bd-fdf102fd0f01,Synergized modular access,Data Engineering,75,1.0,6,16.666667,95,62.55
1981,ff5bc5cd-d4f9-42dc-a94f-7d523327425b,Alexis Roy,Web Developer,ec547ddb-3fec-424b-a343-ddafec1fa0cf,Visionary asymmetric hub,DevOps,95,1.0,2,50.000000,50,62.55
1982,ff5bc5cd-d4f9-42dc-a94f-7d523327425b,Alexis Roy,Web Developer,eee76786-5a72-4d28-9a2e-23266b968959,Digitized high-level throughput,Generative AI,77,3.0,10,30.000000,42,62.55
1983,ff5bc5cd-d4f9-42dc-a94f-7d523327425b,Alexis Roy,Web Developer,fc64aa01-38bb-4ccf-b446-869c1fd3fcf1,Adaptive context-sensitive Local Area Network,Mobile Development,75,4.0,7,57.142857,50,62.55
1984,ff5bc5cd-d4f9-42dc-a94f-7d523327425b,Alexis Roy,Web Developer,fdfb691a-6314-4d16-85d7-a19611600b8a,Ameliorated responsive Local Area Network,DevOps,69,2.0,3,66.666667,75,62.55

In [577]:
employee_performance_kpi.columns

Index(['user_id', 'name', 'designation', 'course_id', 'course_title',
       'course_tag', 'course_duration', 'modules_completed', 'total_modules',
       'completion_percentage', 'course_score', 'performance_score'],
      dtype='object')

In [578]:
employee_performance_kpi.to_csv('data_warehouse/report/employee_performance_kpi.csv', index=False)

Course Completion by Tag

In [579]:
course_completion_by_tag = final_df.groupby(['course_tag']).agg(
    total_courses=('course_id', 'nunique'),
    total_completed_courses=('completion_percentage', lambda x: (x >= 100).sum()),
    average_completion_percentage=('completion_percentage', 'mean')
).reset_index()

display(course_completion_by_tag)

,course_tag,total_courses,total_completed_courses,average_completion_percentage
0,Cybersecurity,1,40,51.255230
1,Data Engineering,1,20,45.849802
2,Data Science,2,49,50.202840
3,DevOps,4,107,50.328117
4,Generative AI,4,101,50.393701
5,Mobile Development,2,44,49.899194
6,UI/UX Design,4,47,50.463189
7,Web Development,2,36,52.361396

Course Enrollment KPI

In [580]:

course_enrollment_kpi = final_df.groupby(['course_id', 'course_title']).agg(
    enrolled_employees=('user_id', 'nunique')
).reset_index()

display(course_enrollment_kpi)

,course_id,course_title,enrolled_employees
0,2191c368-9102-4d66-a668-5ccf7d317509,Reverse-engineered needs-based flexibility,100
1,30197a42-f77e-49c2-8946-4bbd36fbf79d,Multi-channeled stable help-desk,100
2,38782344-4b97-4ab7-a03f-dd9c9e236ffb,Devolved hybrid structure,100
3,3f04b295-f148-4f74-b86f-daa8506c9048,Polarized needs-based success,100
4,3f4c255a-3ed2-4c07-8b82-3fb30c863226,Ergonomic intangible adapter,100
5,445a1b9a-826f-4f65-90f1-7771578fac5f,User-friendly motivating projection,100
6,55ea5fd6-c51a-4923-b390-b1957a50f298,Public-key methodical neural-net,100
7,5b3b1bdd-a35d-435d-8473-0d92dd911d32,Synergistic bottom-line leverage,100
8,699a90ef-bd36-4eb4-8286-15d8ff970eda,Networked asynchronous archive,100
9,6a52ebe0-0cd7-41a8-b825-3704194741a0,Synchronized system-worthy migration,100
10,6e14ec87-40fe-4809-b762-daa4db93dd3f,Reverse-engineered next generation data-warehouse,100
11,a3ddc761-3c41-4f7f-a56e-e575d1bc25ad,Upgradable dedicated flexibility,100
12,a486147a-14bc-495f-b315-8b115d689ce1,Grass-roots tangible frame,100
13,b126a3f1-2b94-4de0-8e8f-596f478c7de3,Cross-group national framework,100
14,db152902-82d6-4ba2-aa87-f7aa9faf0d69,Multi-tiered mission-critical implementation,100
15,df04b2a3-7c27-4f33-b4bd-fdf102fd0f01,Synergized modular access,100
16,ec547ddb-3fec-424b-a343-ddafec1fa0cf,Visionary asymmetric hub,100
17,eee76786-5a72-4d28-9a2e-23266b968959,Digitized high-level throughput,100
18,fc64aa01-38bb-4ccf-b446-869c1fd3fcf1,Adaptive context-sensitive Local Area Network,100
19,fdfb691a-6314-4d16-85d7-a19611600b8a,Ameliorated responsive Local Area Network,100

Course Completion KPI

In [581]:

course_completion_kpi = final_df.groupby(['course_id', 'course_title']).agg(
    total_enrolled=('user_id', 'count'),
    total_completed=('completion_percentage', lambda x: (x >= 100).sum()),
    completion_rate=('completion_percentage', 'mean')
).reset_index()

course_completion_kpi['completion_rate'] = (course_completion_kpi['total_completed'] / course_completion_kpi['total_enrolled']) * 100

display(course_completion_kpi)

,course_id,course_title,total_enrolled,total_completed,completion_rate
0,2191c368-9102-4d66-a668-5ccf7d317509,Reverse-engineered needs-based flexibility,478,40,8.368201
1,30197a42-f77e-49c2-8946-4bbd36fbf79d,Multi-channeled stable help-desk,518,23,4.440154
2,38782344-4b97-4ab7-a03f-dd9c9e236ffb,Devolved hybrid structure,517,13,2.514507
3,3f04b295-f148-4f74-b86f-daa8506c9048,Polarized needs-based success,505,7,1.386139
4,3f4c255a-3ed2-4c07-8b82-3fb30c863226,Ergonomic intangible adapter,499,16,3.206413
5,445a1b9a-826f-4f65-90f1-7771578fac5f,User-friendly motivating projection,508,2,0.393701
6,55ea5fd6-c51a-4923-b390-b1957a50f298,Public-key methodical neural-net,500,21,4.200000
7,5b3b1bdd-a35d-435d-8473-0d92dd911d32,Synergistic bottom-line leverage,501,9,1.796407
8,699a90ef-bd36-4eb4-8286-15d8ff970eda,Networked asynchronous archive,499,24,4.809619
9,6a52ebe0-0cd7-41a8-b825-3704194741a0,Synchronized system-worthy migration,472,29,6.144068
10,6e14ec87-40fe-4809-b762-daa4db93dd3f,Reverse-engineered next generation data-warehouse,544,15,2.757353
11,a3ddc761-3c41-4f7f-a56e-e575d1bc25ad,Upgradable dedicated flexibility,503,19,3.777336
12,a486147a-14bc-495f-b315-8b115d689ce1,Grass-roots tangible frame,491,26,5.295316
13,b126a3f1-2b94-4de0-8e8f-596f478c7de3,Cross-group national framework,503,23,4.572565
14,db152902-82d6-4ba2-aa87-f7aa9faf0d69,Multi-tiered mission-critical implementation,489,33,6.748466
15,df04b2a3-7c27-4f33-b4bd-fdf102fd0f01,Synergized modular access,508,20,3.937008
16,ec547ddb-3fec-424b-a343-ddafec1fa0cf,Visionary asymmetric hub,489,31,6.339468
17,eee76786-5a72-4d28-9a2e-23266b968959,Digitized high-level throughput,496,46,9.274194
18,fc64aa01-38bb-4ccf-b446-869c1fd3fcf1,Adaptive context-sensitive Local Area Network,490,21,4.285714
19,fdfb691a-6314-4d16-85d7-a19611600b8a,Ameliorated responsive Local Area Network,505,26,5.148515

Employee Performance by Course Tag

In [582]:
employee_performance_by_tag = final_df.groupby(['course_tag']).agg(
    average_performance_score=('performance_score', 'mean'),
    total_employees=('user_id', 'nunique'),
    total_courses=('course_id', 'nunique')
).reset_index()

display(employee_performance_by_tag)

,course_tag,average_performance_score,total_employees,total_courses
0,Cybersecurity,59.142470,100,1
1,Data Engineering,59.582379,100,1
2,Data Science,59.439934,100,2
3,DevOps,59.265600,100,4
4,Generative AI,59.499237,100,4
5,Mobile Development,59.764971,100,2
6,UI/UX Design,59.623538,100,4
7,Web Development,59.433222,100,2

Module Completion KPI

In [583]:

module_completion_kpi = final_df.groupby(['course_id', 'course_title', 'module_id', 'module_title']).agg(
    completed_modules=('is_completed', 'sum'),
    total_modules=('module_id', 'count'),
    module_completion_rate=('is_completed', lambda x: (x.sum() / len(x)) * 100),
    total_module_duration=('module_duration', 'sum')
).reset_index()

display(module_completion_kpi)

,course_id,course_title,module_id,module_title,completed_modules,total_modules,module_completion_rate,total_module_duration
0,2191c368-9102-4d66-a668-5ccf7d317509,Reverse-engineered needs-based flexibility,000925fe-e139-4643-b64a-6265fd5775e4,Operative 24hour neural-net,7.0,11,63.636364,132.0
1,2191c368-9102-4d66-a668-5ccf7d317509,Reverse-engineered needs-based flexibility,049fb0ee-f9e7-4d28-8795-ee351ad9cf5b,Stand-alone empowering firmware,1.0,4,25.000000,52.0
2,2191c368-9102-4d66-a668-5ccf7d317509,Reverse-engineered needs-based flexibility,04e69828-19bb-44d9-ac09-bac84ace291c,Versatile value-added algorithm,4.0,8,50.000000,104.0
3,2191c368-9102-4d66-a668-5ccf7d317509,Reverse-engineered needs-based flexibility,0cdbd036-5902-466c-a880-a6aefb28f770,Polarized static portal,1.0,3,33.333333,84.0
4,2191c368-9102-4d66-a668-5ccf7d317509,Reverse-engineered needs-based flexibility,0d1d7c3a-fa4f-4413-bc1b-c3ecaa62d924,De-engineered directional middleware,2.0,6,33.333333,84.0
...,...,...,...,...,...,...,...,...
1984,fdfb691a-6314-4d16-85d7-a19611600b8a,Ameliorated responsive Local Area Network,f2501335-a404-404b-b795-3f2cf1c946e5,Programmable composite software,3.0,4,75.000000,68.0
1985,fdfb691a-6314-4d16-85d7-a19611600b8a,Ameliorated responsive Local Area Network,f30f737d-41be-4960-85e3-26ecd6e3c0f4,Grass-roots directional solution,3.0,4,75.000000,88.0
1986,fdfb691a-6314-4d16-85d7-a19611600b8a,Ameliorated responsive Local Area Network,faea3a68-3428-4384-9f9f-05a2467c07c4,Triple-buffered client-server attitude,3.0,4,75.000000,112.0
1987,fdfb691a-6314-4d16-85d7-a19611600b8a,Ameliorated responsive Local Area Network,fd4cb534-f7f6-4a04-8926-a53fef840c0b,Switchable background algorithm,1.0,5,20.000000,90.0
1988,fdfb691a-6314-4d16-85d7-a19611600b8a,Ameliorated responsive Local Area Network,fd8b7c82-f01c-4c17-a221-cccd8f6a5690,Re-engineered web-enabled project,2.0,5,40.000000,105.0